// User action types
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const UPDATE_FULLNAME = 'UPDATE_FULLNAME'
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY'
export const UPDATE_CITY = 'UPDATE_CITY'
export const UPDATE_STATE = 'UPDATE_STATE'
export const ADD_DATE_CREATED = 'ADD_DATE_CREATED'
export const ADD_ERROR = 'ADD_ERROR'
